### ISSUE TITLE
Bug: Pool.m line 20

### ISSUE THREAD

**Issue by AghaDurrani** [esiriwardane/structural-garch-deploy#7]
code version:
MATLAB version: MATLAB R2020a
Operating System: WINDOWS 10

## Steps To Reproduce

1. Just run the following line in MATLAB R2020a result = sgjr(AIG_cell{:}, zerocurve);

## The expected behavior

possible solution that does the job:

errorMessage =['Undefined function ', char(39),'matlabpool', char(39), ' for input arguments of type ',char(39),'char',char(39),'.'];
          if strcmp(ME.message, errorMessage)

**Comment by AghaDurrani** [comment]
Crash is in line 20:

if strcmp(ME.message, 'Undefined function or variable ''matlabpool''.')

**Comment by capellini** [comment]
Fixed by 80f97b96e46e2337d785d4dee6ce4b68e229043e.
